### ISSUE TITLE
False negative when running `pre-commit run --all-files`

### ISSUE THREAD

**Issue by mscheper** [leoll2/copyright_notice_precommit#10]
I expected the precommit hook to fail, because some of my files still have last year's copyright notice. But instead, it passed. Other, hooks, higher in the YAML file, passed and failed as expected. Am I doing something wrong?

Bash shell output (under Mint 21.3):
```shell
$ git status
[...]
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        [...]
	modified:   .pre-commit-config.yaml
	new file:   copyright.txt

$ pre-commit run --all-files
[...]
copyright-notice..............................................................................Passed
```

.pre-commit-config.yaml:
```yaml
default_language_version:
    python: python3.12

repos:
    # ...
    - repo: https://github.com/leoll2/copyright_notice_precommit
      rev: 0.1.1
      hooks:
          - id: copyright-notice
            args: [--notice=copyright.txt]
````

copyright.txt (in my repo root):
```
Copyright ⓒ 2025 Michael Scheper
```

helloworld/views.py (not staged, which is why I used `run --all-files`):
```python
# vim: set fileencoding=utf-8
# Copyright ⓒ 2024 Michael Scheper

from django.http import HttpResponse

def helloworld_page(request):
    return HttpResponse("Hello, world! This will be awesome!")
```
